# Generated by Django 2.2.2 on 2019-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerround',
            name='round_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerround',
            name='score',
            field=models.IntegerField(),
        ),
    ]
